Repository team-HSGE/hsge-android, pull requests merged in 2022-12, with the labels that each got.

#24 Feature/get locaiton
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/App.kt
  app/src/main/java/com/starters/hsge/network/RetrofitClient.kt
  app/src/main/java/com/starters/hsge/presentation/GlobalApplication.kt
  app/src/main/java/com/starters/hsge/presentation/common/base/BaseFragment.kt
  app/src/main/java/com/starters/hsge/presentation/common/util/LoadingDialog.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/SettingsFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/WithdrawalFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserDistanceFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserLocationFragment.kt
  app/src/main/res/drawable/bg_light_yellow_round_16.xml
  app/src/main/res/drawable/bg_yellow_round_16.xml
  app/src/main/res/drawable/ic_dislike.xml
  app/src/main/res/drawable/ic_like.xml
  app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_dialog_logout.xml
  app/src/main/res/layout/fragment_dialog_splash.xml
  app/src/main/res/layout/fragment_dialog_withdrawal.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_loading_dialog.xml
  app/src/main/res/layout/fragment_user_distance.xml
  app/src/main/res/layout/fragment_user_location.xml
  app/src/main/res/values/strings.xml
Labels: 정은, feat

#27 Feature/main home
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/data/model/DogCard.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/adapter/CardStackAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/network/DogService.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/network/RetrofitApi.kt
  app/src/main/res/drawable/bg_card_gradient.xml
  app/src/main/res/drawable/chip_dislike.xml
  app/src/main/res/drawable/chip_like.xml
  app/src/main/res/drawable/ic_gender_female_black.xml
  app/src/main/res/drawable/ic_gender_female_white.xml
  app/src/main/res/drawable/ic_gender_male_black.xml
  app/src/main/res/drawable/ic_gender_male_white.xml
  app/src/main/res/layout/fragment_dialog_logout.xml
  app/src/main/res/layout/fragment_dog_dislike_tag.xml
  app/src/main/res/layout/fragment_dog_sex.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_user_profile_edit.xml
  app/src/main/res/layout/item_card.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 정은, feat

#28 Feature/dog profile
  app/src/main/java/com/starters/hsge/common/constants/Data.kt
  app/src/main/java/com/starters/hsge/common/constants/DogBreed.kt
  app/src/main/java/com/starters/hsge/common/constants/DogBreedServer.kt
  app/src/main/java/com/starters/hsge/data/api/ImageService.kt
  app/src/main/java/com/starters/hsge/data/repository/DogProfileRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/domain/repository/DogProfileRepository.kt
  app/src/main/java/com/starters/hsge/presentation/common/Const.kt
  app/src/main/java/com/starters/hsge/presentation/dialog/BottomSheetAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/dialog/BottomSheetDialog.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/RegisterViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/DogAgeFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/DogBreedFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/DogDislikeTagFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/DogLikeTagFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/DogNameFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/DogPhotoFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/DogSexFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/viewmodel/RegisterViewModel.kt
  app/src/main/res/color/selector_dislike_chip.xml
  app/src/main/res/color/selector_dislike_text.xml
  app/src/main/res/color/selector_like_chip.xml
  app/src/main/res/drawable/bg_bottom_sheet.xml
  app/src/main/res/drawable/bg_light_blue_r12.xml
  app/src/main/res/drawable/bg_light_gray_r12.xml
  app/src/main/res/drawable/bg_light_red_r12.xml
  app/src/main/res/drawable/bg_light_yellow_r12.xml
  app/src/main/res/drawable/bg_yellow_r12.xml
  app/src/main/res/drawable/ic_back_btn.xml
  app/src/main/res/drawable/ic_bottom_sheet_indicator.xml
  app/src/main/res/drawable/selector_bottom_sheet.xml
  app/src/main/res/drawable/selector_female_button.xml
  app/src/main/res/drawable/selector_male_button.xml
  app/src/main/res/drawable/selector_next_button.xml
  app/src/main/res/layout/fragment_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_dog_age.xml
  app/src/main/res/layout/fragment_dog_breed.xml
  app/src/main/res/layout/fragment_dog_dislike_tag.xml
  app/src/main/res/layout/fragment_dog_like_tag.xml
  app/src/main/res/layout/fragment_dog_name.xml
  app/src/main/res/layout/fragment_dog_photo.xml
  app/src/main/res/layout/fragment_dog_sex.xml
  app/src/main/res/layout/item_bottom_sheet.xml
  app/src/main/res/navigation/nav_graph_register.xml
  app/src/main/res/values/attr.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 서윤, feat

#30 Feature/user profile
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/App.kt
  app/src/main/java/com/starters/hsge/presentation/common/base/BaseFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/RegisterActivity.kt
  app/src/main/java/com/starters/hsge/presentation/register/adapter/UserProfileIconAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserImageFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserNickNameFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserProfileIconFragment.kt
  app/src/main/res/layout/fragment_user_image.xml
  app/src/main/res/layout/fragment_user_nick_name.xml
  app/src/main/res/layout/fragment_user_profile_icon.xml
  app/src/main/res/navigation/nav_graph_register.xml
Labels: 예빈, feat

#31 Feature/signup
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/network/AccessResponse.kt
  app/src/main/java/com/starters/hsge/network/RetrofitClient.kt
  app/src/main/java/com/starters/hsge/presentation/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
Labels: 예빈, feat

#40 Feat/select chips
  app/src/main/java/com/starters/hsge/presentation/register/fragment/DogDislikeTagFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/DogLikeTagFragment.kt
  app/src/main/res/layout/fragment_dog_dislike_tag.xml
  app/src/main/res/layout/fragment_dog_like_tag.xml
Labels: 서윤, feat

#43 Feature/refac splash
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/presentation/common/base/BaseActivity.kt
  app/src/main/java/com/starters/hsge/presentation/dialog/SplashDialogFragment.kt
  app/src/main/java/com/starters/hsge/presentation/splash/SplashActivity.kt
  app/src/main/res/drawable/ic_splash_sep_icon.xml
  app/src/main/res/drawable/ic_splash_sep_title.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_dialog_splash.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/themes.xml
Labels: 예빈, feat

#45 Feature/user nickname
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/network/NicknameInterface.kt
  app/src/main/java/com/starters/hsge/network/NicknameRequest.kt
  app/src/main/java/com/starters/hsge/network/NicknameResponse.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserImageFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserNickNameFragment.kt
  app/src/main/res/layout/fragment_user_nick_name.xml
Labels: 예빈, feat

#46 Chore/edit user profile image
  app/src/main/java/com/starters/hsge/presentation/login/LoginActivity.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserNickNameFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserProfileIconFragment.kt
  app/src/main/res/drawable/ic_dog_profile_1.xml
  app/src/main/res/drawable/ic_dog_profile_10.xml
  app/src/main/res/drawable/ic_dog_profile_11.xml
  app/src/main/res/drawable/ic_dog_profile_12.xml
  app/src/main/res/drawable/ic_dog_profile_13.xml
  app/src/main/res/drawable/ic_dog_profile_14.xml
  app/src/main/res/drawable/ic_dog_profile_15.xml
  app/src/main/res/drawable/ic_dog_profile_2.xml
  app/src/main/res/drawable/ic_dog_profile_3.xml
  app/src/main/res/drawable/ic_dog_profile_4.xml
  app/src/main/res/drawable/ic_dog_profile_5.xml
  app/src/main/res/drawable/ic_dog_profile_6.xml
  app/src/main/res/drawable/ic_dog_profile_7.xml
  app/src/main/res/drawable/ic_dog_profile_8.xml
  app/src/main/res/drawable/ic_dog_profile_9.xml
  app/src/main/res/drawable/ic_profile_icon_1.xml
  app/src/main/res/drawable/ic_profile_icon_2.xml
  app/src/main/res/drawable/ic_profile_icon_3.xml
  app/src/main/res/drawable/ic_profile_icon_4.xml
  app/src/main/res/drawable/ic_profile_icon_5.xml
  app/src/main/res/drawable/ic_profile_icon_6.xml
  app/src/main/res/drawable/ic_profile_icon_7.xml
  app/src/main/res/drawable/ic_profile_icon_8.xml
  app/src/main/res/layout/item_profile_icon.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/navigation/nav_graph_register.xml
Labels: 예빈, chore

#50 Feature/kakao login
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/network/AccessResponse.kt
  app/src/main/java/com/starters/hsge/network/AccessTokenInterface.kt
  app/src/main/java/com/starters/hsge/network/RetrofitClient.kt
  app/src/main/java/com/starters/hsge/presentation/login/LoginActivity.kt
  app/src/main/java/com/starters/hsge/presentation/splash/SplashActivity.kt
Labels: 예빈, feat

#51 UI/dog management
  app/src/main/java/com/starters/hsge/presentation/common/adapter/BindingAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/common/util/CustomDecoration.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/adapter/CardStackAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/management/DogListAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/management/ManagementFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/MyPageFragment.kt
  app/src/main/res/drawable/bg_dialog_gray_stroke_r8.xml
  app/src/main/res/drawable/bg_dialog_red_r8.xml
  app/src/main/res/drawable/bg_dialog_white_r16.xml
  app/src/main/res/drawable/bg_dialog_yellow_r8.xml
  app/src/main/res/drawable/bg_g100_r12.xml
  app/src/main/res/drawable/bg_g100_r14.xml
  app/src/main/res/drawable/bg_g200_r12.xml
  app/src/main/res/drawable/bg_gray_stroke_r4.xml
  app/src/main/res/drawable/bg_light_gray_round_solid.xml
  app/src/main/res/drawable/bg_login_signup_btn.xml
  app/src/main/res/drawable/bg_yellow_stroke_r8.xml
  app/src/main/res/drawable/ic_arrow_drop_down.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_chip_dislike.xml
  app/src/main/res/drawable/ic_chip_like.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/layout/fragment_dialog_logout.xml
  app/src/main/res/layout/fragment_dialog_splash.xml
  app/src/main/res/layout/fragment_dialog_withdrawal.xml
  app/src/main/res/layout/fragment_dog_age.xml
  app/src/main/res/layout/fragment_dog_breed.xml
  app/src/main/res/layout/fragment_dog_profile_edit.xml
  app/src/main/res/layout/fragment_management.xml
  app/src/main/res/layout/fragment_user_location.xml
  app/src/main/res/layout/fragment_user_profile_edit.xml
  app/src/main/res/layout/fragment_withdrawal.xml
  app/src/main/res/layout/item_dog_list.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/attr.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 서윤, ui

#59 Feature/user profile datastore
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/data/repository/RegisterPreferencesRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/domain/repository/RegisterPreferencesRepository.kt
  app/src/main/java/com/starters/hsge/network/AccessRequest.kt
  app/src/main/java/com/starters/hsge/network/AccessResponse.kt
  app/src/main/java/com/starters/hsge/presentation/login/LoginActivity.kt
  app/src/main/java/com/starters/hsge/presentation/register/adapter/UserProfileIconAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserImageFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserNickNameFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserProfileIconFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/viewmodel/RegisterViewModel.kt
Labels: 예빈, feat

#63 Feature/register exception
  app/src/main/java/com/starters/hsge/ApiResult.kt
  app/src/main/java/com/starters/hsge/App.kt
  app/src/main/java/com/starters/hsge/data/api/UserApi.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/SignUpResponse.kt
  app/src/main/java/com/starters/hsge/data/repository/RegisterRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/domain/repository/RegisterRepository.kt
  app/src/main/java/com/starters/hsge/network/RetrofitClient.kt
  app/src/main/java/com/starters/hsge/presentation/common/Const.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/network/RetrofitApi.kt
  app/src/main/java/com/starters/hsge/presentation/register/viewmodel/RegisterViewModel.kt
  app/src/main/res/navigation/nav_graph_register.xml
Labels: 서윤, feat

#65 Chore/edit mypage UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/presentation/main/management/ManagementFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/SettingsFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/userDistance/UserDistanceFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/userLocation/LocationService.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/userLocation/UserLocationFragment.kt
  app/src/main/res/drawable/ic_distance.xml
  app/src/main/res/drawable/ic_dog_profile_manage.xml
  app/src/main/res/drawable/ic_faq.xml
  app/src/main/res/drawable/ic_inquire.xml
  app/src/main/res/drawable/ic_location_setting.xml
  app/src/main/res/drawable/ic_my_page_item_select.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_user_location.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/navigation/nav_graph_register.xml
Labels: 예빈, chore

#66 Feature/signup login
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/App.kt
  app/src/main/java/com/starters/hsge/domain/model/RegisterInfo.kt
  app/src/main/java/com/starters/hsge/network/CheckTokenInterface.kt
  app/src/main/java/com/starters/hsge/network/CheckTokenRequest.kt
  app/src/main/java/com/starters/hsge/network/CheckTokenResponse.kt
  app/src/main/java/com/starters/hsge/network/RetrofitClient.kt
  app/src/main/java/com/starters/hsge/presentation/login/LoginActivity.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/userLocation/UserLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/splash/SplashActivity.kt
Labels: 예빈, feat

#70 Fix/permission storage
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/presentation/register/fragment/DogPhotoFragment.kt
Labels: 서윤, fix

#71 Feature/logout withdrawal
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/data/model/remote/response/DogCardResponse.kt
  app/src/main/java/com/starters/hsge/data/model/remote/response/MyDogResponse.kt
  app/src/main/java/com/starters/hsge/di/NetWorkModule.kt
  app/src/main/java/com/starters/hsge/network/WithdrawalInterface.kt
  app/src/main/java/com/starters/hsge/presentation/common/Const.kt
  app/src/main/java/com/starters/hsge/presentation/login/LoginActivity.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/adapter/CardStackAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/network/RetrofitApi.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/WithdrawalFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/SettingsFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/WithdrawalFragment.kt
  app/src/main/res/layout/fragment_dog_profile_edit.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/item_dog_list.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 예빈, feat

#73 Feature/dog profile edit
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/data/api/EditDogApi.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/EditDogProfileRequest.kt
  app/src/main/java/com/starters/hsge/data/model/remote/response/DogCardResponse.kt
  app/src/main/java/com/starters/hsge/data/repository/EditDogProfileRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/di/NetWorkModule.kt
  app/src/main/java/com/starters/hsge/di/RepositoryModule.kt
  app/src/main/java/com/starters/hsge/domain/repository/EditDogProfileRepository.kt
  app/src/main/java/com/starters/hsge/domain/usecase/PutEditDogProfileUseCase.kt
  app/src/main/java/com/starters/hsge/presentation/dialog/EditNameDialogFragment.kt
  app/src/main/java/com/starters/hsge/presentation/dialog/TagBottomSheetDialog.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/adapter/CardStackAdapter.kt
  app/src/main/res/layout/fragment_dog_profile_edit.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 서윤, feat

#79 Fix/logout_withdrawal
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/SettingsFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/WithdrawalFragment.kt
Labels: 예빈, fix

#78 Fix/register btn
  app/src/main/java/com/starters/hsge/presentation/register/fragment/DogAgeFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/DogBreedFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/DogSexFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserNickNameFragment.kt
Labels: 서윤, fix

#83 Feature/edit user location
  app/src/main/java/com/starters/hsge/data/api/EditLocationApi.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/UserLocationRequest.kt
  app/src/main/java/com/starters/hsge/data/repository/EditLocationRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/di/NetWorkModule.kt
  app/src/main/java/com/starters/hsge/di/RepositoryModule.kt
  app/src/main/java/com/starters/hsge/domain/repository/EditLocationRepository.kt
  app/src/main/java/com/starters/hsge/domain/usecase/PutEditLocationUseCase.kt
  app/src/main/java/com/starters/hsge/presentation/main/location/EditLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/location/EditLocationViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/userLocation/LocationService.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/userLocation/UserLocationFragment.kt
  app/src/main/res/layout/fragment_edit_location.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 서윤, feat

#85 Feature/add dog profile
  app/src/main/java/com/starters/hsge/presentation/main/add/AddDogProfileFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/management/ManagementFragment.kt
  app/src/main/res/drawable/bg_g200_r16.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/layout/fragment_add_dog_profile.xml
  app/src/main/res/layout/fragment_management.xml
  app/src/main/res/menu/toolbar_add_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 서윤, ui

#86 Feature/add edit dog profile
  app/src/main/java/com/starters/hsge/common/constants/DislikeTag.kt
  app/src/main/java/com/starters/hsge/common/constants/LikeTag.kt
  app/src/main/java/com/starters/hsge/data/api/ImageService.kt
  app/src/main/java/com/starters/hsge/data/model/remote/response/MyDogResponse.kt
  app/src/main/java/com/starters/hsge/data/repository/DogOptionRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/data/repository/DogProfileRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/data/repository/EditDogProfileRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/di/NetWorkModule.kt
  app/src/main/java/com/starters/hsge/di/RepositoryModule.kt
  app/src/main/java/com/starters/hsge/domain/repository/DogOptionRepository.kt
  app/src/main/java/com/starters/hsge/domain/repository/DogProfileRepository.kt
  app/src/main/java/com/starters/hsge/domain/repository/EditDogProfileRepository.kt
  app/src/main/java/com/starters/hsge/domain/usecase/GetDislikeTagsUseCase.kt
  app/src/main/java/com/starters/hsge/domain/usecase/GetLikeTagsUseCase.kt
  app/src/main/java/com/starters/hsge/domain/usecase/PutEditDogProfileUseCase.kt
  app/src/main/java/com/starters/hsge/presentation/dialog/TagBottomSheetDialog.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/TagType.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/ViewType.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/userLocation/UserLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/viewmodel/RegisterViewModel.kt
  app/src/main/res/drawable/bg_g200_r14.xml
  app/src/main/res/layout/fragment_dog_profile_edit.xml
  app/src/main/res/layout/item_dog_list.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/themes.xml
Labels: 서윤, feat

#87 Feature/mypage edit user profile
  app/src/main/java/com/starters/hsge/network/UserInfoGetInterface.kt
  app/src/main/java/com/starters/hsge/network/UserInfoGetResponse.kt
  app/src/main/java/com/starters/hsge/network/UserInfoPutInterface.kt
  app/src/main/java/com/starters/hsge/network/UserInfoPutRequest.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/location/EditLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserInfoData.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserLocationData.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/SettingsFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/WithdrawalFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/userDistance/UserDistanceFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/adapter/UserProfileIconAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserImageFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserProfileIconFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/userLocation/UserLocationFragment.kt
  app/src/main/res/drawable/bg_gray_stroke_r4.xml
  app/src/main/res/layout/fragment_edit_location.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_user_profile_edit.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/navigation/nav_graph_register.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 예빈, feat

#88 Feature/notification_permission
  app/src/main/java/com/starters/hsge/presentation/splash/SplashActivity.kt
Labels: 서윤, feat

#92 Feature/add dog profile
  app/src/main/java/com/starters/hsge/data/api/AddDogApi.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/AddDogRequest.kt
  app/src/main/java/com/starters/hsge/data/repository/AddDogProfileRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/data/repository/EditDogProfileRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/di/NetWorkModule.kt
  app/src/main/java/com/starters/hsge/di/RepositoryModule.kt
  app/src/main/java/com/starters/hsge/domain/repository/AddDogProfileRepository.kt
  app/src/main/java/com/starters/hsge/domain/repository/EditDogProfileRepository.kt
  app/src/main/java/com/starters/hsge/domain/usecase/PostAddDogUseCase.kt
  app/src/main/java/com/starters/hsge/domain/usecase/PutEditDogProfileUseCase.kt
  app/src/main/java/com/starters/hsge/presentation/main/add/AddDogProfileFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/add/AddDogProfileViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/management/ManagementFragment.kt
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/layout/fragment_add_dog_profile.xml
  app/src/main/res/layout/fragment_management.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 서윤, feat

#89 Feature/push notification
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/presentation/main/MainActivity.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/push/FirebaseService.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/push/Repo.kt
  app/src/main/java/com/starters/hsge/presentation/main/location/EditLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/adapter/UserProfileIconAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserImageFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserProfileIconFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/userLocation/UserLocationFragment.kt
  app/src/main/res/drawable/test_push_img.png
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 정은, feat

#95 Feature/delete dog profile
  app/src/main/java/com/starters/hsge/data/api/DeleteDogApi.kt
  app/src/main/java/com/starters/hsge/data/repository/DeleteDogRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/di/NetWorkModule.kt
  app/src/main/java/com/starters/hsge/di/RepositoryModule.kt
  app/src/main/java/com/starters/hsge/domain/repository/DeleteDogRepository.kt
  app/src/main/java/com/starters/hsge/domain/usecase/DeleteDogUseCase.kt
  app/src/main/java/com/starters/hsge/presentation/dialog/BaseDialogFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/add/AddDogProfileFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/SettingsFragment.kt
  app/src/main/res/layout/fragment_dialog_base.xml
  app/src/main/res/layout/fragment_dog_profile_edit.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 서윤, feat

#98 Chore/retrofit merge
  app/src/main/java/com/starters/hsge/data/api/CheckTokenApi.kt
  app/src/main/java/com/starters/hsge/data/api/DistanceApi.kt
  app/src/main/java/com/starters/hsge/data/api/HomeDogApi.kt
  app/src/main/java/com/starters/hsge/data/api/IsLikeApi.kt
  app/src/main/java/com/starters/hsge/data/api/LocationApi.kt
  app/src/main/java/com/starters/hsge/data/api/LoginApi.kt
  app/src/main/java/com/starters/hsge/data/api/NicknameApi.kt
  app/src/main/java/com/starters/hsge/data/api/UserApi.kt
  app/src/main/java/com/starters/hsge/data/api/UserInfoGetApi.kt
  app/src/main/java/com/starters/hsge/data/api/UserInfoPutApi.kt
  app/src/main/java/com/starters/hsge/data/api/WithdrawalApi.kt
  app/src/main/java/com/starters/hsge/data/interfaces/CheckTokenInterface.kt
  app/src/main/java/com/starters/hsge/data/interfaces/LoginInterface.kt
  app/src/main/java/com/starters/hsge/data/interfaces/NicknameInterface.kt
  app/src/main/java/com/starters/hsge/data/interfaces/UserInfoGetInterface.kt
  app/src/main/java/com/starters/hsge/data/interfaces/UserInfoPutInterface.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/CheckTokenRequest.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/DistanceRequest.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/IsLikeRequest.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/LoginRequest.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/NicknameRequest.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/UserInfoPutRequest.kt
  app/src/main/java/com/starters/hsge/data/model/remote/response/CheckTokenResponse.kt
  app/src/main/java/com/starters/hsge/data/model/remote/response/LoginResponse.kt
  app/src/main/java/com/starters/hsge/data/model/remote/response/NicknameResponse.kt
  app/src/main/java/com/starters/hsge/data/model/remote/response/SignUpResponse.kt
  app/src/main/java/com/starters/hsge/data/model/remote/response/UserInfoGetResponse.kt
  app/src/main/java/com/starters/hsge/data/repository/RegisterRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/data/service/CheckTokenService.kt
  app/src/main/java/com/starters/hsge/data/service/LoginService.kt
  app/src/main/java/com/starters/hsge/data/service/NicknameService.kt
  app/src/main/java/com/starters/hsge/data/service/UserInfoGetService.kt
  app/src/main/java/com/starters/hsge/data/service/UserInfoPutService.kt
  app/src/main/java/com/starters/hsge/domain/repository/RegisterRepository.kt
  app/src/main/java/com/starters/hsge/network/AccessTokenInterface.kt
  app/src/main/java/com/starters/hsge/network/UserInfoGetInterface.kt
  app/src/main/java/com/starters/hsge/presentation/login/LoginActivity.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/network/RetrofitApi.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserDistanceFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/WithdrawalFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserNickNameFragment.kt
  app/src/main/java/com/starters/hsge/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/fragment_user_distance.xml
  app/src/main/res/layout/fragment_user_location.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/navigation/nav_graph_register.xml
Labels: 예빈, chore

#99 Fix/userlocation
  app/src/main/java/com/starters/hsge/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/location/EditLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/location/EditLocationViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/fragment_edit_location.xml
  app/src/main/res/layout/fragment_user_distance.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 정은, chore

#101 Chore/add_fcm_field
  app/src/main/java/com/starters/hsge/domain/model/RegisterInfo.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserLocationFragment.kt
Labels: 서윤, chore

#103 Feature/fcm token
  app/src/main/java/com/starters/hsge/data/api/FcmDeleteApi.kt
  app/src/main/java/com/starters/hsge/data/api/FcmPostApi.kt
  app/src/main/java/com/starters/hsge/data/interfaces/LoginInterface.kt
  app/src/main/java/com/starters/hsge/data/interfaces/SettingsInterface.kt
  app/src/main/java/com/starters/hsge/data/interfaces/SplashInterface.kt
  app/src/main/java/com/starters/hsge/data/interfaces/WithdrawalInterface.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/FcmPostRequest.kt
  app/src/main/java/com/starters/hsge/data/service/LoginService.kt
  app/src/main/java/com/starters/hsge/data/service/SettingsService.kt
  app/src/main/java/com/starters/hsge/data/service/SplashService.kt
  app/src/main/java/com/starters/hsge/data/service/WithdrawalService.kt
  app/src/main/java/com/starters/hsge/presentation/login/LoginActivity.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/SettingsFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/WithdrawalFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/splash/SplashActivity.kt
Labels: 예빈, feat

#106 UI/report
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/data/service/LoginService.kt
  app/src/main/java/com/starters/hsge/presentation/dialog/ChatReportOtherDialogFragment.kt
  app/src/main/java/com/starters/hsge/presentation/login/LoginActivity.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatReportFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/SettingsFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/WithdrawalFragment.kt
  app/src/main/res/drawable/bg_red_r12.xml
  app/src/main/res/drawable/selector_report_button.xml
  app/src/main/res/layout/fragment_chat_report.xml
  app/src/main/res/layout/fragment_chat_report_other_dialog.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 정은, ui

#107 UI/chat users dogs
  app/src/main/java/com/starters/hsge/presentation/main/chat/PartnerDogsFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/SpecificDogFragment.kt
  app/src/main/res/drawable/bg_white_r24.xml
  app/src/main/res/layout/fragment_chat_partner_dogs.xml
  app/src/main/res/layout/fragment_chat_partner_specific_dog.xml
  app/src/main/res/layout/fragment_dog_profile_edit.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 예빈, ui

#109 Chore/retrofic refactor service
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/data/interfaces/HomeDogInterface.kt
  app/src/main/java/com/starters/hsge/data/interfaces/IsLikeInterface.kt
  app/src/main/java/com/starters/hsge/data/interfaces/distanceInterface.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/IsLikeRequest.kt
  app/src/main/java/com/starters/hsge/data/service/DistanceService.kt
  app/src/main/java/com/starters/hsge/data/service/HomeDogService.kt
  app/src/main/java/com/starters/hsge/data/service/IsLikeService.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/push/FirebaseService.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserDistanceFragment.kt
Labels: 정은, chore

#110 Fix/edit user profile
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserInfoData.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserProfileEditFragment.kt
  app/src/main/res/drawable/ic_circle_camera.xml
  app/src/main/res/drawable/ic_default_img.xml
  app/src/main/res/drawable/ic_dog_profile_edit_btn.xml
  app/src/main/res/layout/fragment_add_dog_profile.xml
  app/src/main/res/layout/fragment_dog_profile_edit.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_user_profile_edit.xml
  app/src/main/res/layout/item_dog_list.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 예빈, fix

#116 Feature/report
  app/build.gradle
  app/src/main/java/com/starters/hsge/data/api/IsLikeApi.kt
  app/src/main/java/com/starters/hsge/data/api/ReportApi.kt
  app/src/main/java/com/starters/hsge/data/interfaces/ReportInterface.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/ReportRequest.kt
  app/src/main/java/com/starters/hsge/data/service/DistanceService.kt
  app/src/main/java/com/starters/hsge/data/service/HomeDogService.kt
  app/src/main/java/com/starters/hsge/data/service/IsLikeService.kt
  app/src/main/java/com/starters/hsge/data/service/ReportService.kt
  app/src/main/java/com/starters/hsge/presentation/dialog/ChatExitBottomSheetDialog.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatReportFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/find/FindFragment.kt
  app/src/main/res/drawable/ic_exit.xml
  app/src/main/res/drawable/ic_report.xml
  app/src/main/res/drawable/ic_unmatch.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_exit_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_chat_report.xml
  app/src/main/res/layout/fragment_find.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 정은, feat

#117 Feature/chat websocket
  app/build.gradle
  app/src/main/java/com/starters/hsge/presentation/common/adapter/ImageBindingAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/add/AddDogProfileFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/adapter/ChatListAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/adapter/LikedPeopleAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/MessageListAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/WebSocketListener.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditFragment.kt
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/menu/toolbar_chatroom_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 서윤, feat

#119 Feat/connect chat fragment
  app/src/main/java/com/starters/hsge/presentation/common/adapter/ImageBindingAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/dialog/ChatExitBottomSheetDialog.kt
  app/src/main/java/com/starters/hsge/presentation/main/add/AddDogProfileFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/PartnerDogsFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/detail/SpecificDogFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/partner/PartnerDogsAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/partner/PartnerDogsFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/report/ChatReportFragment.kt
  app/src/main/res/drawable/ic_exit.xml
  app/src/main/res/drawable/ic_report.xml
  app/src/main/res/drawable/ic_unmatch.xml
  app/src/main/res/layout/fragment_chat_exit_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_chat_report.xml
  app/src/main/res/layout/item_bottom_sheet.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 서윤, feat

#120 Feature/chat list
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/data/api/ChatListApi.kt
  app/src/main/java/com/starters/hsge/data/interfaces/chatListInterface.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/DistanceRequest.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/IsLikeRequest.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/ReportRequest.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/UserLocationRequest.kt
  app/src/main/java/com/starters/hsge/data/model/remote/response/ChatListResponse.kt
  app/src/main/java/com/starters/hsge/data/model/remote/response/DogCardResponse.kt
  app/src/main/java/com/starters/hsge/data/model/remote/response/LikedPeopleResponse.kt
  app/src/main/java/com/starters/hsge/data/service/ChatListService.kt
  app/src/main/java/com/starters/hsge/network/RetrofitClient.kt
  app/src/main/java/com/starters/hsge/presentation/common/Const.kt
  app/src/main/java/com/starters/hsge/presentation/main/MainActivity.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/adapter/ChatListAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/adapter/LikedPeopleAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/push/FirebaseService.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserProfileIconFragment.kt
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/item_liked_people.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 정은, feat

#125 Fix/push
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/data/api/HomeDogApi.kt
  app/src/main/java/com/starters/hsge/data/interfaces/HomeDogInterface.kt
  app/src/main/java/com/starters/hsge/data/interfaces/chatListInterface.kt
  app/src/main/java/com/starters/hsge/data/service/HomeDogService.kt
  app/src/main/java/com/starters/hsge/presentation/main/MainActivity.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/adapter/CardStackAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/push/FirebaseService.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/location/EditLocationFragment.kt
  app/src/main/res/drawable/dog_profile_1.png
  app/src/main/res/drawable/dog_profile_10.png
  app/src/main/res/drawable/dog_profile_11.png
  app/src/main/res/drawable/dog_profile_12.png
  app/src/main/res/drawable/dog_profile_13.png
  app/src/main/res/drawable/dog_profile_14.png
  app/src/main/res/drawable/dog_profile_15.png
  app/src/main/res/drawable/dog_profile_2.png
  app/src/main/res/drawable/dog_profile_3.png
  app/src/main/res/drawable/dog_profile_4.png
  app/src/main/res/drawable/dog_profile_5.png
  app/src/main/res/drawable/dog_profile_6.png
  app/src/main/res/drawable/dog_profile_7.png
  app/src/main/res/drawable/dog_profile_8.png
  app/src/main/res/drawable/dog_profile_9.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/attr.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 정은, fix

#126 Feature/chat stomp
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/data/api/ChatRecordApi.kt
  app/src/main/java/com/starters/hsge/data/repository/ChatListRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/di/NetWorkModule.kt
  app/src/main/java/com/starters/hsge/di/RepositoryModule.kt
  app/src/main/java/com/starters/hsge/domain/repository/ChatListRepository.kt
  app/src/main/java/com/starters/hsge/network/RetrofitClient.kt
  app/src/main/java/com/starters/hsge/presentation/common/Const.kt
  app/src/main/java/com/starters/hsge/presentation/common/adapter/TextBindingAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/MessageInfo.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/MessageListAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/RecyclerViewExtension.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/push/FirebaseService.kt
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/item_message_received.xml
  app/src/main/res/layout/item_message_sent.xml
Labels: 서윤, feat

#129 Feature/shake hand map
  app/build.gradle
  app/libs/libDaumMapAndroid.jar
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/presentation/main/find/CustomBalloonAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/find/FindFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserProfileEditFragment.kt
  app/src/main/jniLibs/arm64-v8a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi-v7a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi/libDaumMapEngineApi.so
  app/src/main/res/drawable/bg_dark_yellow_r12.xml
  app/src/main/res/drawable/bg_g100_right_r8.xml
  app/src/main/res/drawable/ic_current_location.xml
  app/src/main/res/drawable/ic_map_marker.png
  app/src/main/res/drawable/ic_my_location.png
  app/src/main/res/layout/fragment_find.xml
  app/src/main/res/layout/item_map_balloon.xml
Labels: 예빈, feat

#131 Fix/push
  app/src/main/java/com/starters/hsge/data/model/remote/response/ChatListResponse.kt
  app/src/main/java/com/starters/hsge/presentation/main/MainActivity.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/HomeFragment.kt
Labels: 정은, fix

#132 Feature/chat other user info
  app/src/main/java/com/starters/hsge/data/api/ChatRecordApi.kt
  app/src/main/java/com/starters/hsge/data/api/PartnerApi.kt
  app/src/main/java/com/starters/hsge/data/model/remote/response/ChatListResponse.kt
  app/src/main/java/com/starters/hsge/data/repository/ChatListRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/data/repository/PartnerInfoRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/di/NetWorkModule.kt
  app/src/main/java/com/starters/hsge/di/RepositoryModule.kt
  app/src/main/java/com/starters/hsge/domain/repository/ChatListRepository.kt
  app/src/main/java/com/starters/hsge/domain/repository/PartnerInfoRepository.kt
  app/src/main/java/com/starters/hsge/domain/usecase/GetPartnerInfoUseCase.kt
  app/src/main/java/com/starters/hsge/presentation/common/adapter/TextBindingAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/common/adapter/ViewBindingAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/adapter/ChatListAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/main/detail/SpecificDogFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/partner/PartnerDogsAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/partner/PartnerDogsFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/partner/PartnerDogsViewModel.kt
  app/src/main/res/layout/fragment_chat_partner_dogs.xml
  app/src/main/res/layout/fragment_chat_partner_specific_dog.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 서윤, feat

#134 Fix/conflict
  app/src/main/java/com/starters/hsge/data/model/remote/response/ChatListResponse.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomFragment.kt
Labels: 서윤, fix

#137 Feature/shake hand user
  app/src/main/java/com/starters/hsge/data/api/ShakeHandApi.kt
  app/src/main/java/com/starters/hsge/data/interfaces/ShakeHandInterface.kt
  app/src/main/java/com/starters/hsge/data/model/remote/request/CurrentLocationPostRequest.kt
  app/src/main/java/com/starters/hsge/data/model/remote/response/ShakeHandResponse.kt
  app/src/main/java/com/starters/hsge/data/service/ShakeHandService.kt
  app/src/main/java/com/starters/hsge/presentation/main/find/FindFragment.kt
Labels: 예빈, feat

#139 Fix/gallery photo choice
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/presentation/main/add/AddDogProfileFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/management/ManagementFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/partner/PartnerDogsFragment.kt
  app/src/main/res/layout/fragment_add_dog_profile.xml
  app/src/main/res/layout/item_chat_list.xml
  app/src/main/res/values/strings.xml
Labels: 서윤, fix

#141 Fix/solve issue
  app/src/main/java/com/starters/hsge/presentation/dialog/ChatExitBottomSheetDialog.kt
  app/src/main/java/com/starters/hsge/presentation/login/LoginActivity.kt
  app/src/main/java/com/starters/hsge/presentation/main/MainActivity.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/find/FindFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/location/EditLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/report/ChatReportFragment.kt
  app/src/main/java/com/starters/hsge/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: 예빈, fix

#148 [FIX] #122 채팅방 나가기 navigate 이슈 해결
  app/src/main/java/com/starters/hsge/presentation/dialog/ChatExitBottomSheetDialog.kt
Labels: 정은, fix

#149 Fix/set background profile
  app/src/main/java/com/starters/hsge/presentation/main/chat/adapter/ChatListAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserProfileEditFragment.kt
  app/src/main/res/layout/item_chat_list.xml
  app/src/main/res/layout/item_liked_people.xml
Labels: 예빈, fix
