Repository team-HSGE/hsge-android, pull requests merged in 2023-01, with the labels that each got.

#153 Feature/push chat
  app/src/main/java/com/starters/hsge/presentation/dialog/ChatExitBottomSheetDialog.kt
  app/src/main/java/com/starters/hsge/presentation/main/MainActivity.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/push/FirebaseService.kt
  app/src/main/java/com/starters/hsge/presentation/main/report/ChatReportFragment.kt
Labels: 정은, feat

#156 [CHORE] #155 앱 아이콘 변경
  app/src/debug/ic_app_icon-playstore.png
  app/src/debug/ic_app_logo-playstore.png
  app/src/debug/res/drawable/ic_app_icon_background.xml
  app/src/debug/res/drawable/ic_app_logo_background.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_app_logo.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_app_logo_round.xml
  app/src/debug/res/mipmap-hdpi/ic_app_logo.png
  app/src/debug/res/mipmap-hdpi/ic_app_logo_foreground.png
  app/src/debug/res/mipmap-hdpi/ic_app_logo_round.png
  app/src/debug/res/mipmap-mdpi/ic_app_logo.png
  app/src/debug/res/mipmap-mdpi/ic_app_logo_foreground.png
  app/src/debug/res/mipmap-mdpi/ic_app_logo_round.png
  app/src/debug/res/mipmap-xhdpi/ic_app_logo.png
  app/src/debug/res/mipmap-xhdpi/ic_app_logo_foreground.png
  app/src/debug/res/mipmap-xhdpi/ic_app_logo_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_app_logo.png
  app/src/debug/res/mipmap-xxhdpi/ic_app_logo_foreground.png
  app/src/debug/res/mipmap-xxhdpi/ic_app_logo_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_app_logo.png
  app/src/debug/res/mipmap-xxxhdpi/ic_app_logo_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/ic_app_logo_round.png
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/hsge/presentation/main/MainActivity.kt
Labels: 정은, chore

#158 Chore/app icon
  app/src/debug/ic_launcher-playstore.png
  app/src/debug/res/drawable/ic_launcher_background.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_app_logo.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_app_logo_round.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/debug/res/mipmap-hdpi/ic_app_logo.png
  app/src/debug/res/mipmap-hdpi/ic_app_logo_round.png
  app/src/debug/res/mipmap-hdpi/ic_launcher.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-mdpi/ic_app_logo.png
  app/src/debug/res/mipmap-mdpi/ic_app_logo_round.png
  app/src/debug/res/mipmap-mdpi/ic_launcher.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xhdpi/ic_app_logo.png
  app/src/debug/res/mipmap-xhdpi/ic_app_logo_round.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_app_logo.png
  app/src/debug/res/mipmap-xxhdpi/ic_app_logo_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_app_logo.png
  app/src/debug/res/mipmap-xxxhdpi/ic_app_logo_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/debug/res/values/ic_app_logo_background.xml
Labels: chore

#159 Feature/chat empty view
  app/src/main/java/com/starters/hsge/presentation/common/adapter/TextBindingAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomFragment.kt
  app/src/main/res/drawable/bg_g100_r10.xml
  app/src/main/res/drawable/bg_g300_stroke_r20.xml
  app/src/main/res/drawable/bg_light_yellow_r10.xml
  app/src/main/res/drawable/ic_chat_card_stack.xml
  app/src/main/res/drawable/ic_liked_empty.xml
  app/src/main/res/drawable/ic_liked_empty_with_heart.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_partner_specific_dog.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/fragment_dog_profile_edit.xml
  app/src/main/res/layout/item_chat_list.xml
  app/src/main/res/layout/item_message_received.xml
  app/src/main/res/layout/item_message_sent.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/attr.xml
  app/src/main/res/values/strings.xml
Labels: 서윤, feat

#160 UI/progress bar
  app/build.gradle
  app/src/main/assets/lottie_loading_dog.json
  app/src/main/assets/lottie_loading_location.json
  app/src/main/java/com/starters/hsge/presentation/common/base/BaseFragment.kt
  app/src/main/java/com/starters/hsge/presentation/common/util/LoadingDialog.kt
  app/src/main/java/com/starters/hsge/presentation/dialog/ChatExitBottomSheetDialog.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserDistanceFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/location/EditLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/report/ChatReportFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserLocationFragment.kt
  app/src/main/res/layout/dialog_loading_dog.xml
  app/src/main/res/layout/dialog_loading_location.xml
  build.gradle
Labels: 정은, feat

#163 Feature/push shake hand
  app/src/main/java/com/starters/hsge/data/api/ShakeHandApi.kt
  app/src/main/java/com/starters/hsge/data/interfaces/ChatExitInterface.kt
  app/src/main/java/com/starters/hsge/data/interfaces/ShakeHandInterface.kt
  app/src/main/java/com/starters/hsge/data/service/ShakeHandService.kt
  app/src/main/java/com/starters/hsge/presentation/common/base/BaseActivity.kt
  app/src/main/java/com/starters/hsge/presentation/common/base/BaseFragment.kt
  app/src/main/java/com/starters/hsge/presentation/common/extension/ToastExtension.kt
  app/src/main/java/com/starters/hsge/presentation/dialog/ChatExitBottomSheetDialog.kt
  app/src/main/java/com/starters/hsge/presentation/dialog/TagBottomSheetDialog.kt
  app/src/main/java/com/starters/hsge/presentation/login/LoginActivity.kt
  app/src/main/java/com/starters/hsge/presentation/main/add/AddDogProfileFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/find/FindFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserDistanceFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/UserProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/location/EditLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/SettingsFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/settings/WithdrawalFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/report/ChatReportFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/splash/SplashActivity.kt
Labels: 정은, chore

#166 Feature/inquiry
  app/src/main/java/com/starters/hsge/data/api/ShakeHandApi.kt
  app/src/main/java/com/starters/hsge/presentation/main/find/FindFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/InquiryFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/MyPageFragment.kt
  app/src/main/res/drawable/search_guide.png
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/fragment_inquiry.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 정은, ui

#167 Feature/server response
  app/build.gradle
  app/src/main/java/com/starters/hsge/data/api/SignUpApi.kt
  app/src/main/java/com/starters/hsge/data/api/UserApi.kt
  app/src/main/java/com/starters/hsge/data/api/UserDogApi.kt
  app/src/main/java/com/starters/hsge/data/repository/RegisterRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/data/repository/UserDogRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/domain/repository/RegisterRepository.kt
  app/src/main/java/com/starters/hsge/domain/repository/UserDogRepository.kt
  app/src/main/java/com/starters/hsge/domain/repository/UserRepository.kt
  app/src/main/java/com/starters/hsge/presentation/main/add/AddDogProfileFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/add/AddDogProfileViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/main/management/ManagementFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/management/ManagementState.kt
  app/src/main/java/com/starters/hsge/presentation/main/management/ManagementViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/location/EditLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/location/EditLocationViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/viewmodel/RegisterViewModel.kt
  app/src/main/res/layout/fragment_management.xml
  app/src/main/res/navigation/nav_graph.xml
  build.gradle
Labels: 서윤, feat

#170 Feature/add progressbar dialog
  app/src/main/java/com/starters/hsge/presentation/main/add/AddDogProfileFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/edit/DogProfileEditFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/location/EditLocationFragment.kt
  app/src/main/java/com/starters/hsge/presentation/register/fragment/UserLocationFragment.kt
Labels: 서윤, feat

#175 UI/change empty view
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomFragment.kt
  app/src/main/res/drawable/ic_chat_list_empty.xml
  app/src/main/res/drawable/ic_chat_list_empty_bold.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 서윤, ui

#177 Fix/shake hand notice
  app/src/main/java/com/starters/hsge/presentation/dialog/FindNoticeDialogFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/find/FindFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/push/FirebaseService.kt
  app/src/main/res/drawable/ic_notice_close.xml
  app/src/main/res/drawable/ic_shake_hand_dialog_five.png
  app/src/main/res/drawable/ic_shake_hand_dialog_four.png
  app/src/main/res/drawable/ic_shake_hand_dialog_one.png
  app/src/main/res/drawable/ic_shake_hand_dialog_three.png
  app/src/main/res/drawable/ic_shake_hand_dialog_two.png
  app/src/main/res/layout/fragment_find.xml
  app/src/main/res/layout/fragment_find_notice_dialog.xml
Labels: 예빈, fix

#179 Feature/chatting push
  app/src/main/java/com/starters/hsge/network/RetrofitClient.kt
  app/src/main/java/com/starters/hsge/presentation/common/constants/Const.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/ChatFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/chat/adapter/ChatListAdapter.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/find/FindFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/push/FirebaseService.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/hsge/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_settings.xml
Labels: 정은, feat

#180 [FIX] 손흔들기 Dialog 관련 이슈 처리
  app/src/main/java/com/starters/hsge/presentation/main/find/FindFragment.kt
Labels: 예빈, fix

#185 Feature/chatting push distinguish
  app/src/main/java/com/starters/hsge/data/repository/RegisterPreferencesRepositoryImpl.kt
  app/src/main/java/com/starters/hsge/domain/repository/RegisterPreferencesRepository.kt
  app/src/main/java/com/starters/hsge/network/RetrofitClient.kt
  app/src/main/java/com/starters/hsge/presentation/common/constants/Const.kt
  app/src/main/java/com/starters/hsge/presentation/main/MainActivity.kt
  app/src/main/java/com/starters/hsge/presentation/main/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/find/FindFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/home/push/FirebaseService.kt
  app/src/main/java/com/starters/hsge/presentation/register/viewmodel/RegisterViewModel.kt
  app/src/main/java/com/starters/hsge/presentation/splash/SplashActivity.kt
Labels: 정은, feat

#186 UI/dev app info
  app/src/main/java/com/starters/hsge/presentation/main/mypage/AppInfoFragment.kt
  app/src/main/java/com/starters/hsge/presentation/main/mypage/MyPageFragment.kt
  app/src/main/res/drawable/ic_app_info.xml
  app/src/main/res/drawable/ic_faq.xml
  app/src/main/res/layout/fragment_app_info.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 예빈, ui

#188 Fix/shake hand radius
  app/src/main/java/com/starters/hsge/data/api/ShakeHandApi.kt
  app/src/main/java/com/starters/hsge/data/service/ShakeHandService.kt
  app/src/main/java/com/starters/hsge/presentation/main/find/FindFragment.kt
Labels: 예빈, fix

#191 [CHORE] #190 채팅 리스트 프로필 이미지 바인딩 주석 삭제
  app/src/main/java/com/starters/hsge/presentation/main/chat/adapter/ChatListAdapter.kt
Labels: 정은, chore
